config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "plant#show", as: "home"

  post "new" => "plant#new", as: :new_plant
  post "water" => "plant#water", as: :water_plant
  post "sun" => "plant#sun", as: :sun_plant
  post "fertilize" => "plant#fertilize", as: :fertilize_plant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  before_save :define_status

  def message
    return "You win! Your plant is 10 inches tall!" if height >= 10
    return "Your plant is dead! Why did you kill your plant?! YOU MURDERER" unless self.alive?
    "Your plant is #{height} #{"inch".pluralize(height)} tall!"
  end

  def define_status
    self.alive = false if \
      over_exposed? ||
      over_fertilized? ||
      over_watered?
  end

  def over_fertilized?
    number_of_nutrients / number_of_waterings >= 4
  end

  def over_exposed?
    number_of_sunnings / number_of_waterings >= 4
  end

  def over_watered?
    number_of_waterings / number_of_sunnings >= 4
  end

  def height
    inches = 0
    inches +=  number_of_waterings / 2
    inches += number_of_sunnings / 2
    inches += number_of_nutrients / 2
    inches
  end

  def water
    self.number_of_waterings += 1
    self.save
  end

  def sun
    self.number_of_sunnings += 1
    self.save
  end

  def fertilize
    self.number_of_nutrients += 1
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plant_controller.rb
class PlantController < ApplicationController

  def show
    session[:plant_history] = [] if session[:plant_history].nil?
    @plant = Plant.find_or_create_by(id: session[:plant_id])
    session[:plant_id] = @plant.id
    @ids = session[:plant_history]
  end

  def new
    @plant = Plant.create
    session[:plant_id] = @plant.id
    session[:plant_history].unshift(session[:plant_id])
    @ids = session[:plant_history]
    respond_to do |format|
      format.js {
        flash[:action] = "You started over! The plant is new!"
      }
    end
  end

  def water
    @plant = Plant.find_by(id: session[:plant_id])
    @plant.water
    respond_to do |format|
      format.js {
        flash[:action] = "You watered the plant!"
      }
    end
  end

  def sun
    @plant = Plant.find_by(id: session[:plant_id])
    @plant.sun
    respond_to do |format|
      format.js {
        flash[:action] = "You gave the plant some light!"
      }
    end
  end

  def fertilize
    @plant = Plant.find_by(id: session[:plant_id])
    @plant.fertilize
    respond_to do |format|
      format.js {
        flash[:action] = "You fertilized the plant!"
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantSimulation</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant/_action.html.erb
<p><%= flash[:action] %></p>

app/views/plant/_history.html.erb
<% @ids.each do |id| %>
  <% plant = Plant.find(id) %>
  <% unless plant.nil? %>
    <div class="plant col-sm-6">
      <p>Created at: <%= plant.created_at.strftime("%Y-%m-%d") %></p>
      <p>Height: <%= plant.height %> inches</p>
      <p><%= plant.alive? ? "Your plant was still alive." : "Your plant was killed. You murderer." %></p>
    </div>
  <% end %>
<% end %>

app/views/plant/_message.html.erb
<p><%= @plant.message %></p>

app/views/plant/fertilize.js.erb
$("#action").html("<%= j render 'plant/action' %>");
$("#message").html("<%= j render 'plant/message' %>");

app/views/plant/new.js.erb
$("#action").html("<%= j render 'plant/action' %>");
$("#message").html("<%= j render 'plant/message' %>");
$("#history").html("<%= j render 'plant/history'%>");

app/views/plant/show.html.erb
<div id="plant-show", class="container">

  <div class="row justify-content-center">
    <%= link_to "New Plant", new_plant_path, class: "btn btn-lg btn-outline-secondary", method: :post, remote: true %>
  </div>

  <div class="message">
    <div id="action">
    </div>
    <div id="message">
      <%= render "plant/message" %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-4">
      <%= link_to "Water", water_plant_path, class: "btn btn-outline-primary", method: :post, remote: true %>
    </div>
    <div class="col-4">
      <%= link_to "Sun Lamp", sun_plant_path, class: "btn btn-outline-warning", method: :post, remote: true %>
    </div>
    <div class="col-4">
      <%= link_to "Fertilize", fertilize_plant_path, class: "btn btn-outline-success", method: :post, remote: true %>
    </div>
  </div>

  <div class="row" id="history">
    <%= render "plant/history" %>
  </div>

</div>

app/views/plant/sun.js.erb
$("#action").html("<%= j render 'plant/action' %>");
$("#message").html("<%= j render 'plant/message' %>");

app/views/plant/water.js.erb
$("#action").html("<%= j render 'plant/action' %>");
$("#message").html("<%= j render 'plant/message' %>");